const LinksActionTypes = {
	SET_LINK: 'SET_LINK',
	SET_LINK_MULTIPLE: 'SET_LINK_MULTIPLE',
	SET_DEFAULT_LINKS: 'SET_DEFAULT_LINKS',
	UNSET_LINK: 'UNSET_LINK',
	SET_QUICK_LINK: 'SET_QUICK_LINK',
	UNSET_QUICK_LINK: 'UNSET_QUICK_LINK',
	SET_TOTAL_PROFILE_LINKS: 'SET_TOTAL_PROFILE_LINKS',
}

export default LinksActionTypes
